### ISSUE TITLE
Example node on tracking lib

### ISSUE THREAD

**Issue by LeoAnnArbor** [LidarPerception/tracking_lib#1]
This repo is really nicely organized! Good work, guys! I really appreciate you made this open source and I'd like to build upon the tracking lib to work on some of my own projects. I'm wondering if you guys can share one example ROS node exercising the multi-object tracking pipeline? Thanks!

**Comment by Durant35** [comment]
Thanks a lot for your attention. Really busy recently, will try my best to catch up...

**Comment by LeoAnnArbor** [comment]
Thanks! Looking forward to it!

**Comment by Dxxventi** [comment]
Really like the repo. It is neat and structured. But the example ROS node seems still not there yet. Do you mind to share it? Thanks a lot.
