### ISSUE TITLE
Eigen aligning problem

### ISSUE THREAD

**Issue by ipandaxin** [LidarPerception/tracking_lib#5]
When I run tracking_lib on my computer, Eigen aligning problem always happens.I do not know how to fix it.The problem is:

/usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array()
[with T = double; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) =
= 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.

please tell me how to figure it out .Thanks

**Comment by Durant35** [comment]
@WSX-EXCELLENT0 a little hard for me to reproduce your issue.
+ Have you checked your gcc version and tried to reinstall your eigen? In my runnable laptop:
```bash
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ grep "#define EIGEN_[^_]*_VERSION" /usr/include/eigen3/Eigen/src/Core/util/Macros.h
#define EIGEN_WORLD_VERSION 3
#define EIGEN_MAJOR_VERSION 2
#define EIGEN_MINOR_VERSION 92
```

+ Have you tried following suggestion from http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html？
![image](https://user-images.githubusercontent.com/6770853/72199298-1072d300-3475-11ea-9ea4-45f837677f85.png)
    + **gcc-7** is needed, you can install like following: (https://askubuntu.com/questions/859256/how-to-install-gcc-7-or-clang-4-0)
    ```bash
    $ sudo add-apt-repository ppa:jonathonf/gcc-7.1
    $ sudo apt-get update
    $ sudo apt-get install gcc-7 g++-7
    ``` 
    + Then you can easily update to **C++17** at https://github.com/LidarPerception/tracking_lib/blob/master/CMakeLists.txt#L5

**Comment by Durant35** [comment]
@WSX-EXCELLENT0 does this issue still exist?

**Comment by ipandaxin** [comment]
Thanks for your help.I have upgraded gcc on my computer.It immediately worked after I upgraded my gcc.But several days later&nbsp;it failed again for some other reasons .Because I'm at home now,I can not show you the bugs.
 Happy Chinese New Year！！！
  

 

 ------------------ 原始邮件 ------------------
  发件人:&nbsp;"Gary Chan"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年1月31日(星期五) 晚上10:43
 收件人:&nbsp;"LidarPerception/tracking_lib"<tracking_lib@noreply.github.com&gt;;
 抄送:&nbsp;"WSX"<553978446@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [LidarPerception/tracking_lib] Eigen aligning problem (#5)

 

 
@WSX-EXCELLENT0 does this issue still exist?

**Comment by Durant35** [comment]
Reopen a new one later if needed.
