### ISSUE TITLE
Tracking-help Segmentation code

### ISSUE THREAD

**Issue by ShepelIlya** [LidarPerception/tracking_lib#6]
Hello, @Durant35, and thank you for your great work!

Is there a repo with Tracking-help Segmentation code from paper "Tracking and classification of arbitrary objects with bottom-up/top-down detection"? And can you publish that code here? This code is marked as not in this repository yet.

**Comment by Durant35** [comment]
@ShepelIlya Actually all I have implemented are here... https://github.com/LidarPerception/tracking_lib/blob/master/samples/tracking_node.cpp#L92, I do want to make some improvements...but #3

**Comment by ShepelIlya** [comment]
Oh, thank you then. I am closing this issue because it was in readme only.
