### ISSUE TITLE
tracking_lib cannot run well and the rviz cannot display the obj's trajectory

### ISSUE THREAD

**Issue by ryontang** [LidarPerception/tracking_lib#8]
thanks for your sharing of this perception project, after build the whole project, i run the demo of segment_lib, it can run well and display the box and heading angle of obj in the rviz.

But, when it comes to node of tracking_lib, it fails to work properly:

1. when run the file of demo.launch of tracking_lib, it output some errors with red font
![Selection_346](https://user-images.githubusercontent.com/39891618/100619258-d98d0080-3357-11eb-9d3b-bfc0ed52efa7.png)

2. and the rviz interface output:
![Selection_347](https://user-images.githubusercontent.com/39891618/100619558-4b654a00-3358-11eb-9408-19e6aab82887.png)

3. when i use the rqt_graph of ROS print out the relation of topic in nodes, it shows:
![Selection_345](https://user-images.githubusercontent.com/39891618/100619535-430d0f00-3358-11eb-9284-fdbdde5b1f9a.png)

i don't know where is the problem, very appreciate for your help!

**Comment by Durant35** [comment]
have you rerun again？And if failed again，hope to capture the full log of tracking_node.

**Comment by ryontang** [comment]
> have you rerun again？And if failed again，hope to capture the full log of tracking_node.

i just run the launch file of kitti_ros and tracking_lib;

After running a while and capture its log and then use Ctrl+c to stop, the log is:
![Selection_350](https://user-images.githubusercontent.com/39891618/100622997-82d5f580-335c-11eb-8335-43876cf48b95.png)
![Selection_351](https://user-images.githubusercontent.com/39891618/100623021-8b2e3080-335c-11eb-94a2-a9c6104c3433.png)
![Selection_352](https://user-images.githubusercontent.com/39891618/100623037-908b7b00-335c-11eb-9794-5dcca3b36811.png)
![Selection_353](https://user-images.githubusercontent.com/39891618/100623211-cc264500-335c-11eb-85f0-2f779e5a39c6.png)
![Selection_354](https://user-images.githubusercontent.com/39891618/100623234-d5afad00-335c-11eb-9fbf-f15fe19d159e.png)

**Comment by Durant35** [comment]
... I will run the demo this week. And maybe I can remote assist if fine.

**Comment by ryontang** [comment]
> ... I will run the demo this week. And maybe I can remote assist if fine.

Thanks a lot, May I ask you when will you do this work, please contact me at that time if  it is convenient for you!

**Comment by ryontang** [comment]
> maybe I can remote assist if fine.
hello, I'm sorry to disturb you. i just want to seek for your help and don't know when it's convenient for you to run the demo.

**Comment by Durant35** [comment]
> ... I will run the demo this week. And maybe I can remote assist if fine.

@ryontang No exception on my PC, Ubuntu16.04 Kinetic and PCL1.9

**Comment by ryontang** [comment]
> No exception on my PC, Ubuntu16.04 Kinetic and PCL1.9

all right,  thanks for your rerun, i still have this kind of problem, i don't know where is the problem

**Comment by ryontang** [comment]
> > No exception on my PC, Ubuntu16.04 Kinetic and PCL1.9
> 
> all right, thanks for your rerun, i still have this kind of problem, i don't know where is the problem

refers to the subcriber between nodes, it seems have no problem, how do you debug your project use ide?

**Comment by Durant35** [comment]
no ide... maybe due to pcl...you build it release？
catkin build -DCMAKE_BUILD_TYPE=Release

**Comment by ryontang** [comment]
> no ide... maybe due to pcl...you build it release？
> catkin build -DCMAKE_BUILD_TYPE=Release

ok, i have a try,  thanks a lot!

**Comment by ryontang** [comment]
> > no ide... maybe due to pcl...you build it release？
> > catkin build -DCMAKE_BUILD_TYPE=Release
> 
> ok, i have a try, thanks a lot!
Sorry to bother you !

Actually, the PCL is 1.9 in my pc, and i have tried to build a new workspace and git clone the src file, according to the steps in README.md of project tracking libs(also use catkin build -DCMAKE_BUILD_TYPE=Release):

I roslaunch the kitti_play.launch and the demo.launch of tracking_lib, it still report the same errors, as i display the picture of log record above. 

but strangely,  then i  roslaunch the kitti_play.launch and the demo.launch of segment_lib, it run normally.

**Comment by ryontang** [comment]
> no ide... maybe due to pcl...you build it release？
> catkin build -DCMAKE_BUILD_TYPE=Releasefind_package(PCL REQUIRED

Thanking for your remote assist last time, and helping me find the problem that is the references of PCL, I just uninstalled PCL 1.9, and changed find_package(PCL 1.8 REQUIRED)  to find_package(PCL REQUIRED). 

At last, the whole project runs well!
